version: 1.0.{build}

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

configuration:
  - Release
  - Debug

platform:
  - x64

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ..

build:
  project: C:\projects\checklist-server\build\checklist-server.sln
  parallel: true
  verbosity: normal

artifacts:
  - path: build\bin\Release\server.exe
  - path: build\bin\Debug\server.exe